//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rainfall.Test.Config {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rainfall.Test.Config.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;@context&quot;: &quot;http://environment.data.gov.uk/flood-monitoring/meta/context.jsonld&quot;,
        ///  &quot;meta&quot;: {
        ///    &quot;publisher&quot;: &quot;Environment Agency&quot;,
        ///    &quot;licence&quot;: &quot;http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/&quot;,
        ///    &quot;documentation&quot;: &quot;http://environment.data.gov.uk/flood-monitoring/doc/reference&quot;,
        ///    &quot;version&quot;: &quot;0.9&quot;,
        ///    &quot;comment&quot;: &quot;Status: Beta service&quot;,
        ///    &quot;hasFormat&quot;: [
        ///      &quot;http://environment.data.gov.uk/flood-monitoring/id/stations/3680/readings.csv?_sorted&amp;_limit=1000&quot;,
        ///      &quot;ht [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SortedRainfallApi_Response {
            get {
                return ResourceManager.GetString("SortedRainfallApi_Response", resourceCulture);
            }
        }
    }
}
